[package]
name = "point-sort"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.2"
metaheuristics = "1.1.22"
rand = "0.8.5"
time = "0.3.17"
walkdir = "2.3.2"
xflags = "0.3.1"
nanoserde = "0.1.32"
